config/routes.rb
Rails.application.routes.draw do
  

  resources :three_d_files
   root "three_d_files#index"

   get 'oembed/:id' , to: 'oembed#show', defaults: { format: 'json' }, as: 'oembed'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/three_d_file.rb
class ThreeDFile < ApplicationRecord

mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
 validates :name,:attachment , presence: true # Make sure the owner's name is present.   

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oembed_controller.rb
class OembedController < ApplicationController
    #include Blacklight::AccessControls::Catalog

    #before_action :set_headers

    def show
      threedfile = ThreeDFile.find(params[:id])

      threedfile.name
      threedfile.id

      embed_url = url_for(three_d_file_url(threedfile))

      # Build up a JSON response with the required attributes
      # See "2.3.4. Response parameters" at https://oembed.com/
      @response = {
        type: 'rich',
        version: '1.0',
        title: threedfile.name,
        provider_name: 'DRI: Digital Repository of Ireland',
        provider_url: 'https://repository.dri.ie/',
        width: 560,
        height: 315,
        # Embedding url

        html: <<-HTML
        <iframe src = "#{embed_url}" width="560px" height="315px">
        </iframe>
        HTML
      }

      respond_to do |format|
        if @response
          format.json { render json: @response }
          format.xml  { render xml: @response }
        else
          format.all  { raise Exception } 
        end
      end
   end

      def set_headers
        response.headers["Access-Control-Allow-Origin"] = "*"
      end
 end

app/controllers/three_d_files_controller.rb
class ThreeDFilesController < ApplicationController
   def index   
      @ThreeDFiles = ThreeDFile.all   
   end   
      
   def new   
      @ThreeDFile = ThreeDFile.new   
   end   
      
   def create   
      @ThreeDFile = ThreeDFile.new(threedfile_params)   
         
      if @ThreeDFile.save   
      	 flash.notice = "Successfully loaded" 
         redirect_to three_d_files_path  
      else   
         render "new"   
      end   
         
   end   
      
   def destroy   
      @ThreeDFile = ThreeDFile.find(params[:id])   
      @ThreeDFile.destroy
      flash.notice = "Successfully deleted"
      redirect_to three_d_files_path  
   end   
      
  def show
  	 @ThreeDFile = ThreeDFile.find(params[:id])   
     
  end	

   private  

   def threedfile_params 

      params.require(:three_d_file).permit(:name, :attachment)   
   
   end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/three_d_files_helper.rb
module ThreeDFilesHelper
end

app/helpers/three_d_helper.rb
module ThreeDHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DRI3dviewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <p id = "notice"> <%= notice%> </p>

 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/three_d/index.html.erb
<script>
const uploadForm = document.querySelector('.upload')
uploadForm.addEventListener('submit', function(e) {
   e.preventDefault()
   let file = e.target.uploadFile.files[0]
   let formData = new FormData()
   formData.append('file', file)
   fetch('http://localhost:3000/upload_files', {
      method: 'POST',
      body: formData
   })
   .then(data => {
      if (data.errors) {
         alert(data.errors)
      }
      else {
         console.log(data)
      }
   })
})
 </script> 



<form class="upload">
   <input type="file" name="uploadFile" />
   <br/><br/>
   <input type="submit" />
</form>

app/views/three_d_files/_error_list.html.erb
<% if @ThreeDFile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ThreeDFile.errors.count, "error") %> prohibited this Model from being uploaded </h2>

      <ul>
      <% @ThreeDFile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/three_d_files/create.html.erb
<h1>ThreeDFiles#create</h1>
<p>Find me in app/views/three_d_files/create.html.erb</p>

app/views/three_d_files/destroy.html.erb
<h1>ThreeDFiles#destroy</h1>
<p>Find me in app/views/three_d_files/destroy.html.erb</p>

app/views/three_d_files/index.html.erb
  <head>
  
   
    <style> 
      body { margin: 0; } canvas { display: block; }

     </style>
    
    
    <%= javascript_include_tag 'lib/STLLoader',media: 'all' %> 
    <%= javascript_include_tag 'lib/GLTFLoader',media: 'all' %> 
    <%= javascript_include_tag 'lib/PCDLoader.js',media: 'all' %> 
    <%= javascript_include_tag 'lib/dat.gui.min.js',media: 'all' %> 


  </head>


<div class="content">   
<% if !flash[:notice].blank? %>   
   <div>   
      <%= flash[:notice] %>   
   </div>   
<% end %>   
  
<br>   
  <h3>
<%= link_to "Upload 3D Model", new_three_d_file_url %>   </h3>
<br>   
<br>   
  
<table border="1" >   
   <thead>   
      <tr>
         <th style="text-align:center">Sr. No</th>    
         <th style="text-align:center">Title</th>   
         <th style="text-align:center">Action </th>   
 
      </tr>   
   </thead>   
      
   <tbody>   
      <% @ThreeDFiles.each do |threedfile| %>   
            
         <tr> 

           <td><%= threedfile.id %></td>     
            <td><%= threedfile.name %></td>   
            
            <td><%= link_to "Delete",  threedfile, method: :delete, confirm: "Are you sure you want to delete #{threedfile.name}?" %>
            

             <%= link_to "Show", three_d_file_path(threedfile)  %>
             
             <%= link_to "Embed", oembed_path(threedfile.id) %></td>
         </tr>   
            
      <% end %>   
   </tbody>   
      
</table>   
</div>  

app/views/three_d_files/new.html.erb
<%= render 'error_list' %>  
  
<div class ="content">   

<h1 >Upload 3D Model</h1>
   <%= form_for @ThreeDFile, html: { multipart: true } do |f| %>   
    <p> <%= f.label :name %>  
     <%= f.text_field :name %>  </p>   
      <br> 
  <p align = "left">  
  	
  	<%= f.label :attachment %>  
   <div class ="attachment"> <%= f.file_field :attachment %> </div>
      <br>   
       </p>
      <%= f.submit "Submit" %>   
   <% end %>   
 
  
</div>  

app/views/three_d_files/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Three</title>
   
    <style> 
      body { margin: 0; } canvas { display: block; }

     </style>
   
    <%= javascript_include_tag 'lib/OrbitControls' ,media: 'all'%> 
    <%= javascript_include_tag 'lib/STLLoader',media: 'all' %> 
    <%= javascript_include_tag 'lib/GLTFLoader',media: 'all' %> 
    <%= javascript_include_tag 'lib/PCDLoader.js',media: 'all' %> 
    <%= javascript_include_tag 'lib/dat.gui.min.js',media: 'all' %> 

  </head>
  <body>

 <script type="text/javascript">

// Necessary for camera/plane rotation
var degree = Math.PI/180;
var  cameraTarget ,container;


container = document.createElement( 'div' );
document.body.appendChild( container );

// Setup
var scene = new THREE.Scene();

var camera = new THREE.PerspectiveCamera(100, window.innerWidth / window.innerHeight, 1, 1000);
camera.position.set( 3, 0.15, 3 );
cameraTarget = new THREE.Vector3( 0, - 0.25, 0 );


var renderer = new THREE.WebGLRenderer({antialias: true});
renderer.shadowMap.enabled = true;
renderer.setPixelRatio(window.devicePixelRatio); 
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.outputEncoding = THREE.sRGBEncoding;

//document.body.appendChild(renderer.domElement);

renderer.shadowMap.enabled = true;
container.appendChild( renderer.domElement );


scene.background = new THREE.Color( 0x72645b );

// Resize after viewport-size-change



window.addEventListener( 'resize', onWindowResize, false );



// Adding controls
controls = new THREE.OrbitControls(camera, renderer.domElement);


  
// Ground (comment out line: "scene.add( plane );" if Ground is not needed...)
var plane = new THREE.Mesh(
    new THREE.PlaneBufferGeometry(150, 150),
    new THREE.MeshPhongMaterial( { color: 0x999999, specular: 0x101010 } )
);
//plane.rotation.x = -30 * degree;
//plane.position.y = 0;
//scene.add( plane );
plane.rotation.x = - Math.PI / 2;
plane.position.y = - 4;
scene.add( plane );
//plane.receiveShadow = true;

var url = '<%= @ThreeDFile.attachment_url%>';
url = 'http://localhost:3000' + url;
// ASCII file - STL Import
var loader = new THREE.STLLoader();


loader.load( url, function ( geometry ) {
    var material = getMaterial('phong', 0xff5533, 0x111111, 200);
    var mesh = new THREE.Mesh( geometry, material );
    mesh.position.set( 0, - 0.25, 0.6 );
    mesh.rotation.set( - Math.PI / 2, 0, 0 );
    mesh.scale.set( 0.5, 0.5, 0.5 );
    scene.add( mesh );
    mesh.castShadow = true;
	mesh.receiveShadow = true;
 
 
} );




// Camera positioning
camera.position.z = 120;
camera.position.y = 120;
camera.rotation.x = -45 * degree;

// Ambient light (necessary for Phong/Lambert-materials, not for Basic)
//var ambientLight = new THREE.AmbientLight( 0x00ff00, 1);  // model color
//scene.add(ambientLight);

// Add lights
var hemiLight = new THREE.HemisphereLight( 0x443333, 0x111122, 0.61 );
hemiLight.position.set( 0, 50, 0 );
// Add hemisphere light to scene   
scene.add( hemiLight );


addShadowedLight( 1, 1, 1, 0xffffff, 1.35 );
addShadowedLight( 0.5, 1, - 1, 0xffaa00, 1 );

//var dirLight = new THREE.DirectionalLight( 0x00ff00, 0.54 );
//    dirLight.position.set( -8, 12, 8 );
//    dirLight.castShadow = true;
//    dirLight.shadow.mapSize = new THREE.Vector2(1024, 1024);
// Add directional Light to scene    
//    scene.add( dirLight );



// Draw scene
var render = function () {

	//var timer = Date.now() * 0.0005;

	//camera.position.x = Math.cos( timer ) * 3;
	//camera.position.z = Math.sin( timer ) * 3;

	camera.lookAt( cameraTarget );
    renderer.render(scene, camera);
};

// Run game loop (render,repeat)
var GameLoop = function () {
   
    requestAnimationFrame(GameLoop);
    render();


};


function onWindowResize() {

camera.aspect = window.innerWidth / window.innerHeight;
camera.updateProjectionMatrix();
renderer.setSize( window.innerWidth, window.innerHeight );

}



function addShadowedLight( x, y, z, color, intensity ) {

				var directionalLight = new THREE.DirectionalLight( color, intensity );
				directionalLight.position.set( x, y, z );
				scene.add( directionalLight );

				directionalLight.castShadow = true;

				var d = 1;
				directionalLight.shadow.camera.left = - d;
				directionalLight.shadow.camera.right = d;
				directionalLight.shadow.camera.top = d;
				directionalLight.shadow.camera.bottom = - d;

				directionalLight.shadow.camera.near = 1;
				directionalLight.shadow.camera.far = 4;

				directionalLight.shadow.bias = - 0.002;

			}

function getMaterial(type, color) {
	var selectedMaterial;
	var materialOptions = {
		color: color === undefined ? 'rgb(255, 255, 255)' : color,
	};

	switch (type) {
		case 'basic':
			selectedMaterial = new THREE.MeshBasicMaterial(materialOptions);
			break;
		case 'lambert':
			selectedMaterial = new THREE.MeshLambertMaterial(materialOptions);
			break;
		case 'phong':
			selectedMaterial = new THREE.MeshPhongMaterial(materialOptions);
			break;
		case 'standard':
			selectedMaterial = new THREE.MeshStandardMaterial(materialOptions);
			break;
		default: 
			selectedMaterial = new THREE.MeshBasicMaterial(materialOptions);
			break;
	}

	return selectedMaterial;
}



GameLoop();







</script>

    <%= yield %>
  </body>
</html>